/*
Copyright 2022 The efucloud.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/efucloud/api/rbac/v1alpha1/generated.proto

package v1alpha1

import (
	fmt "fmt"

	io "io"

	proto "github.com/gogo/protobuf/proto"
	v11 "k8s.io/api/rbac/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *KubeUser) Reset()      { *m = KubeUser{} }
func (*KubeUser) ProtoMessage() {}
func (*KubeUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_c42a1ded9dff3a30, []int{0}
}
func (m *KubeUser) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KubeUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *KubeUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubeUser.Merge(m, src)
}
func (m *KubeUser) XXX_Size() int {
	return m.Size()
}
func (m *KubeUser) XXX_DiscardUnknown() {
	xxx_messageInfo_KubeUser.DiscardUnknown(m)
}

var xxx_messageInfo_KubeUser proto.InternalMessageInfo

func (m *KubeUserList) Reset()      { *m = KubeUserList{} }
func (*KubeUserList) ProtoMessage() {}
func (*KubeUserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c42a1ded9dff3a30, []int{1}
}
func (m *KubeUserList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KubeUserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *KubeUserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubeUserList.Merge(m, src)
}
func (m *KubeUserList) XXX_Size() int {
	return m.Size()
}
func (m *KubeUserList) XXX_DiscardUnknown() {
	xxx_messageInfo_KubeUserList.DiscardUnknown(m)
}

var xxx_messageInfo_KubeUserList proto.InternalMessageInfo

func (m *KubeUserSpec) Reset()      { *m = KubeUserSpec{} }
func (*KubeUserSpec) ProtoMessage() {}
func (*KubeUserSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_c42a1ded9dff3a30, []int{2}
}
func (m *KubeUserSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KubeUserSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *KubeUserSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubeUserSpec.Merge(m, src)
}
func (m *KubeUserSpec) XXX_Size() int {
	return m.Size()
}
func (m *KubeUserSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_KubeUserSpec.DiscardUnknown(m)
}

var xxx_messageInfo_KubeUserSpec proto.InternalMessageInfo

func (m *KubeUserStatus) Reset()      { *m = KubeUserStatus{} }
func (*KubeUserStatus) ProtoMessage() {}
func (*KubeUserStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_c42a1ded9dff3a30, []int{3}
}
func (m *KubeUserStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KubeUserStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *KubeUserStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubeUserStatus.Merge(m, src)
}
func (m *KubeUserStatus) XXX_Size() int {
	return m.Size()
}
func (m *KubeUserStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_KubeUserStatus.DiscardUnknown(m)
}

var xxx_messageInfo_KubeUserStatus proto.InternalMessageInfo

func (m *UserKubeConfig) Reset()      { *m = UserKubeConfig{} }
func (*UserKubeConfig) ProtoMessage() {}
func (*UserKubeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c42a1ded9dff3a30, []int{4}
}
func (m *UserKubeConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserKubeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *UserKubeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserKubeConfig.Merge(m, src)
}
func (m *UserKubeConfig) XXX_Size() int {
	return m.Size()
}
func (m *UserKubeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_UserKubeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_UserKubeConfig proto.InternalMessageInfo

func (m *UserKubeConfigList) Reset()      { *m = UserKubeConfigList{} }
func (*UserKubeConfigList) ProtoMessage() {}
func (*UserKubeConfigList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c42a1ded9dff3a30, []int{5}
}
func (m *UserKubeConfigList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserKubeConfigList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *UserKubeConfigList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserKubeConfigList.Merge(m, src)
}
func (m *UserKubeConfigList) XXX_Size() int {
	return m.Size()
}
func (m *UserKubeConfigList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserKubeConfigList.DiscardUnknown(m)
}

var xxx_messageInfo_UserKubeConfigList proto.InternalMessageInfo

func (m *UserKubeConfigSpec) Reset()      { *m = UserKubeConfigSpec{} }
func (*UserKubeConfigSpec) ProtoMessage() {}
func (*UserKubeConfigSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_c42a1ded9dff3a30, []int{6}
}
func (m *UserKubeConfigSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserKubeConfigSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *UserKubeConfigSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserKubeConfigSpec.Merge(m, src)
}
func (m *UserKubeConfigSpec) XXX_Size() int {
	return m.Size()
}
func (m *UserKubeConfigSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_UserKubeConfigSpec.DiscardUnknown(m)
}

var xxx_messageInfo_UserKubeConfigSpec proto.InternalMessageInfo

func (m *UserKubeConfigStatus) Reset()      { *m = UserKubeConfigStatus{} }
func (*UserKubeConfigStatus) ProtoMessage() {}
func (*UserKubeConfigStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_c42a1ded9dff3a30, []int{7}
}
func (m *UserKubeConfigStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserKubeConfigStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *UserKubeConfigStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserKubeConfigStatus.Merge(m, src)
}
func (m *UserKubeConfigStatus) XXX_Size() int {
	return m.Size()
}
func (m *UserKubeConfigStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UserKubeConfigStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UserKubeConfigStatus proto.InternalMessageInfo

func (m *WorkspaceRole) Reset()      { *m = WorkspaceRole{} }
func (*WorkspaceRole) ProtoMessage() {}
func (*WorkspaceRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_c42a1ded9dff3a30, []int{8}
}
func (m *WorkspaceRole) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WorkspaceRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *WorkspaceRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkspaceRole.Merge(m, src)
}
func (m *WorkspaceRole) XXX_Size() int {
	return m.Size()
}
func (m *WorkspaceRole) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkspaceRole.DiscardUnknown(m)
}

var xxx_messageInfo_WorkspaceRole proto.InternalMessageInfo

func (m *WorkspaceRoleList) Reset()      { *m = WorkspaceRoleList{} }
func (*WorkspaceRoleList) ProtoMessage() {}
func (*WorkspaceRoleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c42a1ded9dff3a30, []int{9}
}
func (m *WorkspaceRoleList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WorkspaceRoleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *WorkspaceRoleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkspaceRoleList.Merge(m, src)
}
func (m *WorkspaceRoleList) XXX_Size() int {
	return m.Size()
}
func (m *WorkspaceRoleList) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkspaceRoleList.DiscardUnknown(m)
}

var xxx_messageInfo_WorkspaceRoleList proto.InternalMessageInfo

func (m *WorkspaceRoleSpec) Reset()      { *m = WorkspaceRoleSpec{} }
func (*WorkspaceRoleSpec) ProtoMessage() {}
func (*WorkspaceRoleSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_c42a1ded9dff3a30, []int{10}
}
func (m *WorkspaceRoleSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WorkspaceRoleSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *WorkspaceRoleSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkspaceRoleSpec.Merge(m, src)
}
func (m *WorkspaceRoleSpec) XXX_Size() int {
	return m.Size()
}
func (m *WorkspaceRoleSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkspaceRoleSpec.DiscardUnknown(m)
}

var xxx_messageInfo_WorkspaceRoleSpec proto.InternalMessageInfo

func init() {
	proto.RegisterType((*KubeUser)(nil), "github.com.efucloud.api.rbac.v1alpha1.KubeUser")
	proto.RegisterType((*KubeUserList)(nil), "github.com.efucloud.api.rbac.v1alpha1.KubeUserList")
	proto.RegisterType((*KubeUserSpec)(nil), "github.com.efucloud.api.rbac.v1alpha1.KubeUserSpec")
	proto.RegisterType((*KubeUserStatus)(nil), "github.com.efucloud.api.rbac.v1alpha1.KubeUserStatus")
	proto.RegisterType((*UserKubeConfig)(nil), "github.com.efucloud.api.rbac.v1alpha1.UserKubeConfig")
	proto.RegisterType((*UserKubeConfigList)(nil), "github.com.efucloud.api.rbac.v1alpha1.UserKubeConfigList")
	proto.RegisterType((*UserKubeConfigSpec)(nil), "github.com.efucloud.api.rbac.v1alpha1.UserKubeConfigSpec")
	proto.RegisterType((*UserKubeConfigStatus)(nil), "github.com.efucloud.api.rbac.v1alpha1.UserKubeConfigStatus")
	proto.RegisterType((*WorkspaceRole)(nil), "github.com.efucloud.api.rbac.v1alpha1.WorkspaceRole")
	proto.RegisterType((*WorkspaceRoleList)(nil), "github.com.efucloud.api.rbac.v1alpha1.WorkspaceRoleList")
	proto.RegisterType((*WorkspaceRoleSpec)(nil), "github.com.efucloud.api.rbac.v1alpha1.WorkspaceRoleSpec")
}

func init() {
	proto.RegisterFile("github.com/efucloud/api/rbac/v1alpha1/generated.proto", fileDescriptor_c42a1ded9dff3a30)
}

var fileDescriptor_c42a1ded9dff3a30 = []byte{
	// 1133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x4f, 0x6f, 0xe3, 0xc4,
	0x1b, 0xae, 0xd3, 0x24, 0xbf, 0x64, 0x92, 0x6c, 0x7f, 0x9d, 0x6d, 0x97, 0xa8, 0x12, 0x4e, 0x14,
	0x58, 0x14, 0x21, 0x70, 0x68, 0xd9, 0xa2, 0xa2, 0x15, 0x87, 0x4d, 0x36, 0x82, 0x55, 0x83, 0xa8,
	0xa6, 0xad, 0x56, 0x14, 0x56, 0x62, 0xe2, 0x4c, 0x1c, 0x6f, 0x1c, 0xdb, 0x78, 0xc6, 0x85, 0xdc,
	0xf6, 0x03, 0x70, 0xe0, 0xcc, 0x91, 0xcf, 0xc0, 0x27, 0xe0, 0xd4, 0x03, 0xa0, 0x3d, 0xee, 0x29,
	0xa2, 0xe1, 0x0b, 0x70, 0x44, 0x9c, 0xd0, 0x8c, 0xc7, 0xb1, 0x1d, 0x92, 0x92, 0xf6, 0xd0, 0x5b,
	0xfd, 0xbe, 0xcf, 0xfb, 0xbc, 0xff, 0xe6, 0x7d, 0xaa, 0x80, 0x7d, 0xc3, 0x64, 0x03, 0xbf, 0xab,
	0xe9, 0xce, 0xa8, 0x41, 0xfa, 0xbe, 0x6e, 0x39, 0x7e, 0xaf, 0x81, 0x5d, 0xb3, 0xe1, 0x75, 0xb1,
	0xde, 0x38, 0xdf, 0xc5, 0x96, 0x3b, 0xc0, 0xbb, 0x0d, 0x83, 0xd8, 0xc4, 0xc3, 0x8c, 0xf4, 0x34,
	0xd7, 0x73, 0x98, 0x03, 0xef, 0x47, 0x61, 0x5a, 0x18, 0xa6, 0x61, 0xd7, 0xd4, 0x78, 0x98, 0x16,
	0x86, 0xed, 0xbc, 0x1b, 0x63, 0x37, 0x1c, 0xc3, 0x69, 0x88, 0xe8, 0xae, 0xdf, 0x17, 0x5f, 0xe2,
	0x43, 0xfc, 0x15, 0xb0, 0xee, 0xd4, 0x86, 0x07, 0x54, 0x33, 0x9d, 0x78, 0xfe, 0xf9, 0xcc, 0x3b,
	0x0f, 0x22, 0xcc, 0x08, 0xeb, 0x03, 0xd3, 0x26, 0xde, 0xb8, 0xe1, 0x0e, 0x0d, 0x6e, 0xa0, 0x8d,
	0x11, 0x61, 0x78, 0x51, 0xd4, 0x07, 0xcb, 0xa2, 0x3c, 0xdf, 0x66, 0xe6, 0x88, 0x34, 0xa8, 0x3e,
	0x20, 0x23, 0x3c, 0x1f, 0x57, 0xfb, 0x31, 0x05, 0x72, 0x87, 0x7e, 0x97, 0x9c, 0x52, 0xe2, 0xc1,
	0xaf, 0x40, 0x8e, 0xf3, 0xf7, 0x30, 0xc3, 0x65, 0xa5, 0xaa, 0xd4, 0x0b, 0x7b, 0xef, 0x69, 0x01,
	0xaf, 0x16, 0xe7, 0xd5, 0xdc, 0xa1, 0xc1, 0x0d, 0x54, 0xe3, 0x68, 0xed, 0x7c, 0x57, 0xfb, 0xac,
	0xfb, 0x9c, 0xe8, 0xec, 0x53, 0xc2, 0x70, 0x13, 0x5e, 0x4c, 0x2a, 0x6b, 0xd3, 0x49, 0x05, 0x44,
	0x36, 0x34, 0x63, 0x85, 0xa7, 0x20, 0x4d, 0x5d, 0xa2, 0x97, 0x53, 0x82, 0xfd, 0x7d, 0x6d, 0xa5,
	0x29, 0x6b, 0x61, 0x81, 0xc7, 0x2e, 0xd1, 0x9b, 0x45, 0x99, 0x20, 0xcd, 0xbf, 0x90, 0xa0, 0x83,
	0xcf, 0x40, 0x96, 0x32, 0xcc, 0x7c, 0x5a, 0x5e, 0x17, 0xc4, 0xfb, 0xd7, 0x25, 0x16, 0xc1, 0xcd,
	0x3b, 0x92, 0x3a, 0x1b, 0x7c, 0x23, 0x49, 0x5a, 0xfb, 0x59, 0x01, 0xc5, 0x10, 0xda, 0x31, 0x29,
	0x83, 0x5f, 0xfe, 0x6b, 0x50, 0xda, 0x6a, 0x83, 0xe2, 0xd1, 0x62, 0x4c, 0xff, 0x97, 0xa9, 0x72,
	0xa1, 0x25, 0x36, 0xa4, 0x13, 0x90, 0x31, 0x19, 0x19, 0xd1, 0x72, 0xaa, 0xba, 0x5e, 0x2f, 0xec,
	0x35, 0xae, 0xd9, 0x4c, 0xb3, 0x24, 0xb9, 0x33, 0x4f, 0x38, 0x0b, 0x0a, 0xc8, 0x6a, 0x2f, 0x52,
	0x51, 0x13, 0x7c, 0x74, 0xf0, 0x1d, 0x90, 0xf3, 0x29, 0xf1, 0x6c, 0x3c, 0x22, 0xa2, 0x89, 0x7c,
	0x54, 0xd4, 0xa9, 0xb4, 0xa3, 0x19, 0x02, 0xbe, 0x01, 0x32, 0x64, 0x84, 0x4d, 0x4b, 0xac, 0x2e,
	0x1f, 0xe5, 0x68, 0x73, 0x23, 0x0a, 0x7c, 0x9c, 0xd2, 0xc2, 0xb6, 0xe1, 0x63, 0x83, 0x88, 0x4d,
	0xc4, 0x28, 0x3b, 0xd2, 0x8e, 0x66, 0x08, 0x4e, 0xe9, 0x0e, 0x1c, 0x9b, 0x94, 0xd3, 0x49, 0xca,
	0x23, 0x6e, 0x44, 0x81, 0x0f, 0xbe, 0x05, 0xb2, 0xc4, 0xc6, 0x5d, 0x8b, 0x94, 0x33, 0x55, 0xa5,
	0x9e, 0x8e, 0x76, 0xd4, 0x16, 0x56, 0x24, 0xbd, 0xb0, 0x06, 0xb2, 0x86, 0xe7, 0xf8, 0x2e, 0x2d,
	0x67, 0xab, 0xeb, 0xf5, 0x7c, 0x13, 0x70, 0xcc, 0xc7, 0xc2, 0x82, 0xa4, 0xa7, 0xf6, 0x43, 0x0a,
	0xdc, 0x49, 0xae, 0x1c, 0xea, 0xa0, 0x64, 0x61, 0xca, 0x3a, 0x8e, 0x61, 0xda, 0x27, 0xa6, 0x9c,
	0x44, 0x61, 0xef, 0xed, 0xd5, 0xd6, 0xc9, 0x23, 0x9a, 0x9b, 0xd3, 0x49, 0xa5, 0xd4, 0x89, 0x93,
	0xa0, 0x24, 0x27, 0x3c, 0x00, 0x45, 0x6e, 0x40, 0x64, 0xe4, 0x30, 0xf2, 0xc4, 0x95, 0x23, 0xdc,
	0x92, 0x9d, 0x14, 0x3b, 0x91, 0xef, 0x08, 0x25, 0x90, 0xb1, 0xee, 0xf9, 0x38, 0x73, 0x4b, 0xbb,
	0x7f, 0x04, 0x36, 0x5c, 0x4c, 0xe9, 0x37, 0x8e, 0xd7, 0x6b, 0xdb, 0xba, 0x37, 0x76, 0x99, 0x1c,
	0xea, 0x6b, 0x32, 0x60, 0xe3, 0x28, 0xe9, 0x46, 0xf3, 0xf8, 0xda, 0x4f, 0x29, 0x70, 0x87, 0x0f,
	0x86, 0x0f, 0xa8, 0xe5, 0xd8, 0x7d, 0xd3, 0xb8, 0x05, 0x3d, 0xf8, 0x22, 0xa1, 0x07, 0x1f, 0xae,
	0xf8, 0xd2, 0x93, 0x65, 0x2e, 0x55, 0x05, 0x7d, 0x4e, 0x15, 0x1e, 0xde, 0x8c, 0xfe, 0x6a, 0x6d,
	0xf8, 0x4d, 0x01, 0x30, 0x19, 0x70, 0x0b, 0x0a, 0x71, 0x96, 0x54, 0x88, 0xfd, 0x1b, 0x35, 0xb6,
	0x44, 0x27, 0xfe, 0x4c, 0xcd, 0x37, 0x24, 0xd4, 0x62, 0x1f, 0x14, 0x86, 0xf2, 0x74, 0x10, 0xe9,
	0x4b, 0xc1, 0xb8, 0x2b, 0x19, 0x0a, 0x87, 0x91, 0x0b, 0xc5, 0x71, 0x70, 0x0f, 0x00, 0xdd, 0xf2,
	0x29, 0x0b, 0xa2, 0x82, 0x87, 0x3f, 0x7b, 0x12, 0xad, 0x99, 0x07, 0xc5, 0x50, 0xf0, 0x19, 0x28,
	0x90, 0x6f, 0x5d, 0xd3, 0x23, 0x3d, 0x71, 0x91, 0xeb, 0xd7, 0xbe, 0xc8, 0x0d, 0x5e, 0x52, 0x3b,
	0xa2, 0x40, 0x71, 0x3e, 0x78, 0x0c, 0xb6, 0x75, 0xcb, 0x24, 0x36, 0x6b, 0x11, 0x8f, 0x99, 0x7d,
	0x53, 0xc7, 0x8c, 0x3c, 0xe6, 0x7b, 0xca, 0x88, 0xea, 0x5e, 0x97, 0xd5, 0x6d, 0xb7, 0x16, 0x81,
	0xd0, 0xe2, 0x58, 0xf8, 0x10, 0x94, 0x02, 0xc7, 0x21, 0x19, 0x0b, 0xb2, 0xac, 0x20, 0xdb, 0x96,
	0x64, 0xa5, 0x56, 0xdc, 0x89, 0x92, 0xd8, 0xda, 0x77, 0x69, 0xb0, 0xb5, 0xe8, 0xd1, 0xc5, 0xce,
	0x5f, 0xb9, 0xf2, 0xfc, 0x1b, 0x20, 0x8f, 0xcf, 0xb1, 0x69, 0x09, 0x68, 0x4a, 0x40, 0x37, 0x25,
	0x34, 0xff, 0x28, 0x74, 0xa0, 0x08, 0x03, 0x0f, 0x40, 0x9a, 0x8d, 0xdd, 0x50, 0xa4, 0xdf, 0x0c,
	0x8f, 0xe7, 0x64, 0xec, 0x92, 0xbf, 0x27, 0x95, 0x2d, 0x44, 0xbe, 0xf6, 0x09, 0x65, 0x2d, 0xc7,
	0xee, 0x99, 0xcc, 0x74, 0x6c, 0x6e, 0x47, 0x22, 0x82, 0x97, 0xa4, 0x53, 0xb1, 0xcc, 0x60, 0x5c,
	0xb3, 0x92, 0x5a, 0xc7, 0x88, 0x2f, 0x52, 0x7a, 0x61, 0x15, 0xa4, 0x07, 0x98, 0x0e, 0xe4, 0x1c,
	0x66, 0xe7, 0xf9, 0x09, 0xa6, 0x03, 0x24, 0x3c, 0xf0, 0x39, 0x50, 0x49, 0xa0, 0x3d, 0xa4, 0xb7,
	0x70, 0xd6, 0xe5, 0xff, 0x55, 0x95, 0x7a, 0xb1, 0x59, 0x9b, 0x4e, 0x2a, 0x6a, 0xfb, 0x4a, 0x24,
	0xfa, 0x0f, 0x26, 0x88, 0xc0, 0xbd, 0x39, 0x44, 0xb8, 0xa7, 0x9c, 0xc8, 0xb1, 0x33, 0x9d, 0x54,
	0xee, 0xb5, 0x17, 0x22, 0xd0, 0x92, 0x48, 0xf8, 0x14, 0xe4, 0xb9, 0x56, 0xb7, 0x06, 0x44, 0x1f,
	0x96, 0xf3, 0xd7, 0x7e, 0xa4, 0x25, 0xbe, 0x9c, 0x4e, 0x48, 0x80, 0x22, 0xae, 0xda, 0xaf, 0x0a,
	0x28, 0x3d, 0x75, 0xbc, 0x21, 0x75, 0xb1, 0x4e, 0x90, 0x63, 0x91, 0x5b, 0x10, 0xe2, 0xb3, 0x84,
	0x10, 0x1f, 0xac, 0x28, 0x28, 0x89, 0x2a, 0x97, 0xe9, 0x70, 0xed, 0x17, 0x05, 0x6c, 0x26, 0x90,
	0xb7, 0xa0, 0x90, 0x9f, 0x27, 0x15, 0xf2, 0xc1, 0x4d, 0x1a, 0x5a, 0x22, 0x90, 0x7f, 0xcd, 0xb7,
	0x23, 0xf4, 0xb1, 0x05, 0x32, 0x9e, 0x6f, 0x11, 0x5a, 0x56, 0x44, 0x42, 0x35, 0xd6, 0x4b, 0x98,
	0x43, 0x3b, 0x72, 0x2c, 0x53, 0x1f, 0x23, 0x3f, 0x4e, 0xcd, 0xbf, 0x28, 0x0a, 0x62, 0xe1, 0x47,
	0x60, 0x23, 0xd4, 0x41, 0xc7, 0x22, 0x88, 0xf4, 0x83, 0xfa, 0xf3, 0xcd, 0xbb, 0xfc, 0x5f, 0x78,
	0x2b, 0xe9, 0x42, 0xf3, 0x58, 0xae, 0xd1, 0x3d, 0x42, 0x75, 0xcf, 0x74, 0xf9, 0xd1, 0xca, 0xe3,
	0x9e, 0x69, 0xf4, 0xe3, 0xc8, 0x85, 0xe2, 0x38, 0x58, 0x07, 0x39, 0x2f, 0x4c, 0x97, 0x16, 0xe9,
	0x8a, 0x7c, 0xaa, 0xb3, 0x3c, 0x33, 0x6f, 0xf3, 0xf0, 0xe2, 0x52, 0x5d, 0x7b, 0x79, 0xa9, 0xae,
	0xbd, 0xba, 0x54, 0xd7, 0x5e, 0x4c, 0x55, 0xe5, 0x62, 0xaa, 0x2a, 0x2f, 0xa7, 0xaa, 0xf2, 0x6a,
	0xaa, 0x2a, 0xbf, 0x4f, 0x55, 0xe5, 0xfb, 0x3f, 0xd4, 0xb5, 0xb3, 0xfb, 0x2b, 0xfd, 0xe4, 0xfa,
	0x27, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xf6, 0xf0, 0x81, 0x9a, 0x0d, 0x00, 0x00,
}

func (m *KubeUser) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KubeUser) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KubeUser) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *KubeUserList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KubeUserList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KubeUserList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *KubeUserSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KubeUserSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KubeUserSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Groups) > 0 {
		for iNdEx := len(m.Groups) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Groups[iNdEx])
			copy(dAtA[i:], m.Groups[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(m.Groups[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	i = encodeVarintGenerated(dAtA, i, uint64(m.Enable))
	i--
	dAtA[i] = 0x28
	i -= len(m.Phone)
	copy(dAtA[i:], m.Phone)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Phone)))
	i--
	dAtA[i] = 0x22
	i -= len(m.Language)
	copy(dAtA[i:], m.Language)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Language)))
	i--
	dAtA[i] = 0x1a
	i -= len(m.Email)
	copy(dAtA[i:], m.Email)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Email)))
	i--
	dAtA[i] = 0x12
	i -= len(m.Username)
	copy(dAtA[i:], m.Username)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Username)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *KubeUserStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KubeUserStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KubeUserStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.PasswordEncrypt)
	copy(dAtA[i:], m.PasswordEncrypt)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.PasswordEncrypt)))
	i--
	dAtA[i] = 0x22
	i--
	if m.Enable {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x18
	i -= len(m.LastRemoteIP)
	copy(dAtA[i:], m.LastRemoteIP)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.LastRemoteIP)))
	i--
	dAtA[i] = 0x12
	if m.LastLoginTime != nil {
		{
			size, err := m.LastLoginTime.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UserKubeConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserKubeConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserKubeConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *UserKubeConfigList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserKubeConfigList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserKubeConfigList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *UserKubeConfigSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserKubeConfigSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserKubeConfigSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.ClientKeyData)
	copy(dAtA[i:], m.ClientKeyData)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.ClientKeyData)))
	i--
	dAtA[i] = 0x32
	i -= len(m.ClientCertificateData)
	copy(dAtA[i:], m.ClientCertificateData)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.ClientCertificateData)))
	i--
	dAtA[i] = 0x2a
	if m.ExpiredTime != nil {
		{
			size, err := m.ExpiredTime.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	i -= len(m.ClusterRef)
	copy(dAtA[i:], m.ClusterRef)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.ClusterRef)))
	i--
	dAtA[i] = 0x12
	i -= len(m.KubeUserRef)
	copy(dAtA[i:], m.KubeUserRef)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.KubeUserRef)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *UserKubeConfigStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserKubeConfigStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserKubeConfigStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastCheck != nil {
		{
			size, err := m.LastCheck.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.EncryptedClientKeyData != nil {
		i -= len(m.EncryptedClientKeyData)
		copy(dAtA[i:], m.EncryptedClientKeyData)
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.EncryptedClientKeyData)))
		i--
		dAtA[i] = 0x42
	}
	if m.EncryptedClientCertificateData != nil {
		i -= len(m.EncryptedClientCertificateData)
		copy(dAtA[i:], m.EncryptedClientCertificateData)
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.EncryptedClientCertificateData)))
		i--
		dAtA[i] = 0x3a
	}
	i -= len(m.Hash)
	copy(dAtA[i:], m.Hash)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Hash)))
	i--
	dAtA[i] = 0x32
	i -= len(m.CSRRef)
	copy(dAtA[i:], m.CSRRef)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.CSRRef)))
	i--
	dAtA[i] = 0x2a
	i -= len(m.Type)
	copy(dAtA[i:], m.Type)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Type)))
	i--
	dAtA[i] = 0x1a
	i--
	if m.Available {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x10
	i--
	if m.Enable {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *WorkspaceRole) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WorkspaceRole) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WorkspaceRole) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *WorkspaceRoleList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WorkspaceRoleList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WorkspaceRoleList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *WorkspaceRoleSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WorkspaceRoleSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WorkspaceRoleSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RoleRefs) > 0 {
		for iNdEx := len(m.RoleRefs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RoleRefs[iNdEx])
			copy(dAtA[i:], m.RoleRefs[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(m.RoleRefs[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	i -= len(m.Description)
	copy(dAtA[i:], m.Description)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Description)))
	i--
	dAtA[i] = 0x1a
	if len(m.ClusterRoleRefs) > 0 {
		for iNdEx := len(m.ClusterRoleRefs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ClusterRoleRefs[iNdEx])
			copy(dAtA[i:], m.ClusterRoleRefs[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(m.ClusterRoleRefs[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Rules) > 0 {
		for iNdEx := len(m.Rules) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rules[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *KubeUser) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *KubeUserList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *KubeUserSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Email)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Language)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Phone)
	n += 1 + l + sovGenerated(uint64(l))
	n += 1 + sovGenerated(uint64(m.Enable))
	if len(m.Groups) > 0 {
		for _, s := range m.Groups {
			l = len(s)
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *KubeUserStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LastLoginTime != nil {
		l = m.LastLoginTime.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	l = len(m.LastRemoteIP)
	n += 1 + l + sovGenerated(uint64(l))
	n += 2
	l = len(m.PasswordEncrypt)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *UserKubeConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *UserKubeConfigList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *UserKubeConfigSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.KubeUserRef)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.ClusterRef)
	n += 1 + l + sovGenerated(uint64(l))
	if m.ExpiredTime != nil {
		l = m.ExpiredTime.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	l = len(m.ClientCertificateData)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.ClientKeyData)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *UserKubeConfigStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 2
	n += 2
	l = len(m.Type)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.CSRRef)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Hash)
	n += 1 + l + sovGenerated(uint64(l))
	if m.EncryptedClientCertificateData != nil {
		l = len(m.EncryptedClientCertificateData)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.EncryptedClientKeyData != nil {
		l = len(m.EncryptedClientKeyData)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.LastCheck != nil {
		l = m.LastCheck.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *WorkspaceRole) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *WorkspaceRoleList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *WorkspaceRoleSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Rules) > 0 {
		for _, e := range m.Rules {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.ClusterRoleRefs) > 0 {
		for _, s := range m.ClusterRoleRefs {
			l = len(s)
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	l = len(m.Description)
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.RoleRefs) > 0 {
		for _, s := range m.RoleRefs {
			l = len(s)
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *KubeUser) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&KubeUser{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "KubeUserSpec", "KubeUserSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "KubeUserStatus", "KubeUserStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *KubeUserList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]KubeUser{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "KubeUser", "KubeUser", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&KubeUserList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *KubeUserSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&KubeUserSpec{`,
		`Username:` + fmt.Sprintf("%v", this.Username) + `,`,
		`Email:` + fmt.Sprintf("%v", this.Email) + `,`,
		`Language:` + fmt.Sprintf("%v", this.Language) + `,`,
		`Phone:` + fmt.Sprintf("%v", this.Phone) + `,`,
		`Enable:` + fmt.Sprintf("%v", this.Enable) + `,`,
		`Groups:` + fmt.Sprintf("%v", this.Groups) + `,`,
		`}`,
	}, "")
	return s
}
func (this *KubeUserStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&KubeUserStatus{`,
		`LastLoginTime:` + strings.Replace(fmt.Sprintf("%v", this.LastLoginTime), "Time", "v1.Time", 1) + `,`,
		`LastRemoteIP:` + fmt.Sprintf("%v", this.LastRemoteIP) + `,`,
		`Enable:` + fmt.Sprintf("%v", this.Enable) + `,`,
		`PasswordEncrypt:` + fmt.Sprintf("%v", this.PasswordEncrypt) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UserKubeConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UserKubeConfig{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "UserKubeConfigSpec", "UserKubeConfigSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "UserKubeConfigStatus", "UserKubeConfigStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UserKubeConfigList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]UserKubeConfig{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "UserKubeConfig", "UserKubeConfig", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&UserKubeConfigList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *UserKubeConfigSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UserKubeConfigSpec{`,
		`KubeUserRef:` + fmt.Sprintf("%v", this.KubeUserRef) + `,`,
		`ClusterRef:` + fmt.Sprintf("%v", this.ClusterRef) + `,`,
		`ExpiredTime:` + strings.Replace(fmt.Sprintf("%v", this.ExpiredTime), "Time", "v1.Time", 1) + `,`,
		`ClientCertificateData:` + fmt.Sprintf("%v", this.ClientCertificateData) + `,`,
		`ClientKeyData:` + fmt.Sprintf("%v", this.ClientKeyData) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UserKubeConfigStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UserKubeConfigStatus{`,
		`Enable:` + fmt.Sprintf("%v", this.Enable) + `,`,
		`Available:` + fmt.Sprintf("%v", this.Available) + `,`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`CSRRef:` + fmt.Sprintf("%v", this.CSRRef) + `,`,
		`Hash:` + fmt.Sprintf("%v", this.Hash) + `,`,
		`EncryptedClientCertificateData:` + valueToStringGenerated(this.EncryptedClientCertificateData) + `,`,
		`EncryptedClientKeyData:` + valueToStringGenerated(this.EncryptedClientKeyData) + `,`,
		`LastCheck:` + strings.Replace(fmt.Sprintf("%v", this.LastCheck), "Time", "v1.Time", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *WorkspaceRole) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&WorkspaceRole{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "WorkspaceRoleSpec", "WorkspaceRoleSpec", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *WorkspaceRoleList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]WorkspaceRole{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "WorkspaceRole", "WorkspaceRole", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&WorkspaceRoleList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *WorkspaceRoleSpec) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForRules := "[]PolicyRule{"
	for _, f := range this.Rules {
		repeatedStringForRules += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForRules += "}"
	s := strings.Join([]string{`&WorkspaceRoleSpec{`,
		`Rules:` + repeatedStringForRules + `,`,
		`ClusterRoleRefs:` + fmt.Sprintf("%v", this.ClusterRoleRefs) + `,`,
		`Description:` + fmt.Sprintf("%v", this.Description) + `,`,
		`RoleRefs:` + fmt.Sprintf("%v", this.RoleRefs) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *KubeUser) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KubeUser: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KubeUser: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KubeUserList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KubeUserList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KubeUserList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, KubeUser{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KubeUserSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KubeUserSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KubeUserSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Language", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Language = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Phone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enable", wireType)
			}
			m.Enable = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Enable |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Groups", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Groups = append(m.Groups, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KubeUserStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KubeUserStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KubeUserStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastLoginTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastLoginTime == nil {
				m.LastLoginTime = &v1.Time{}
			}
			if err := m.LastLoginTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastRemoteIP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastRemoteIP = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enable = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PasswordEncrypt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PasswordEncrypt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserKubeConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserKubeConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserKubeConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserKubeConfigList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserKubeConfigList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserKubeConfigList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, UserKubeConfig{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserKubeConfigSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserKubeConfigSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserKubeConfigSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KubeUserRef", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KubeUserRef = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterRef", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClusterRef = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiredTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExpiredTime == nil {
				m.ExpiredTime = &v1.Time{}
			}
			if err := m.ExpiredTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientCertificateData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientCertificateData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientKeyData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientKeyData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserKubeConfigStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserKubeConfigStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserKubeConfigStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enable = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Available", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Available = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = RequestConditionType(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CSRRef", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CSRRef = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedClientCertificateData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptedClientCertificateData = append(m.EncryptedClientCertificateData[:0], dAtA[iNdEx:postIndex]...)
			if m.EncryptedClientCertificateData == nil {
				m.EncryptedClientCertificateData = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedClientKeyData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptedClientKeyData = append(m.EncryptedClientKeyData[:0], dAtA[iNdEx:postIndex]...)
			if m.EncryptedClientKeyData == nil {
				m.EncryptedClientKeyData = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCheck", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastCheck == nil {
				m.LastCheck = &v1.Time{}
			}
			if err := m.LastCheck.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WorkspaceRole) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WorkspaceRole: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WorkspaceRole: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WorkspaceRoleList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WorkspaceRoleList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WorkspaceRoleList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, WorkspaceRole{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WorkspaceRoleSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WorkspaceRoleSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WorkspaceRoleSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rules", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rules = append(m.Rules, v11.PolicyRule{})
			if err := m.Rules[len(m.Rules)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterRoleRefs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClusterRoleRefs = append(m.ClusterRoleRefs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoleRefs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoleRefs = append(m.RoleRefs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
