/*
Copyright 2022 The efucloud.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-generated-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_CoderTemplate = map[string]string{
	"": "CoderTemplate is the Schema for the CoderTemplates API",
}

func (CoderTemplate) SwaggerDoc() map[string]string {
	return map_CoderTemplate
}

var map_CoderTemplateList = map[string]string{
	"": "CoderTemplateList contains a list of CoderTemplate",
}

func (CoderTemplateList) SwaggerDoc() map[string]string {
	return map_CoderTemplateList
}

var map_CoderTemplateSpec = map[string]string{
	"":            "CoderTemplateSpec defines the desired state of CoderTemplate",
	"name":        "template name",
	"description": "template description",
	"author":      "template' image author",
	"language":    "template language",
	"containers":  "template containers",
}

func (CoderTemplateSpec) SwaggerDoc() map[string]string {
	return map_CoderTemplateSpec
}

var map_CoderTemplateStatus = map[string]string{
	"": "CoderTemplateStatus defines the observed state of CoderTemplate",
}

func (CoderTemplateStatus) SwaggerDoc() map[string]string {
	return map_CoderTemplateStatus
}

var map_CoderVirt = map[string]string{
	"": "CoderVirt is the Schema for the CoderVirts API",
}

func (CoderVirt) SwaggerDoc() map[string]string {
	return map_CoderVirt
}

var map_CoderVirtList = map[string]string{
	"": "CoderVirtList contains a list of CoderVirt",
}

func (CoderVirtList) SwaggerDoc() map[string]string {
	return map_CoderVirtList
}

var map_CoderVirtSpec = map[string]string{
	"": "CoderVirtSpec defines the desired state of CoderVirt",
}

func (CoderVirtSpec) SwaggerDoc() map[string]string {
	return map_CoderVirtSpec
}

var map_CoderVirtStatus = map[string]string{
	"": "CoderVirtStatus defines the observed state of CoderVirt",
}

func (CoderVirtStatus) SwaggerDoc() map[string]string {
	return map_CoderVirtStatus
}

// AUTO-GENERATED FUNCTIONS END HERE
